name: Builds

on:
  release:
    types: [created]
jobs:

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.10.1', '8.8.3', '8.6.5'] # , '8.4.4']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        exclude:
          - os: windows-latest
            ghc: '8.8.3' # fails due to segfault

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-haskell@v1.1.1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: '3.2'
    - run: cabal update

    # - name: Cache Cabal
    #   uses: actions/cache@v1.2.0
    #   with:
    #     path: ~/.cabal
    #     key: ${{ runner.OS }}-${{ matrix.ghc }}-cabal-0
  

    - name: Build
      run: cabal build exe:haskell-language-server
          
    - name: Find binary
      id: find_binary
      shell: bash
      run: |
        HLS=$(find dist-newstyle \( -name 'haskell-language-server' -o -name 'haskell-language-server.exe' \) -type f)
        echo ::set-output name=hls_binary::$HLS

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.find_binary.outputs.hls_binary }}
        asset_name: haskell-language-server-${{ runner.OS }}-${{ matrix.ghc }}
        asset_content_type: application/octet-stream
